name: Build and deploy Next.js 15 app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPP_NAME: "notetaking"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install --force

      - name: Build the Next.js app
        run: npm run build

      - name: Prepare deployment output
        run: |
          mkdir -p output/.next/static

          echo "Copying standalone files..."
          cp -R .next/standalone/* output/

          echo "Copying static assets..."
          cp -R .next/static output/.next/static

          echo "Copying BUILD_ID..."
          cp .next/BUILD_ID output/.next/BUILD_ID

          echo "Copying public directory (if exists)..."
          [ -d public ] && cp -R public output/public

          echo "Copying package.json..."
          cp package.json output/

      - name: Inspect and validate deployment output
        run: |
          echo "==================== 📁 Deployment Output ===================="
          sudo apt-get update && sudo apt-get install tree -y
          tree output || echo "⚠️ 'tree' not available"

          echo ""
          echo "==================== ✅ Critical File Checks ===================="
          test -f output/server.js && echo "✅ Found: server.js" || (echo "❌ Missing: server.js" && exit 1)
          test -f output/.next/BUILD_ID && echo "✅ Found: .next/BUILD_ID" || (echo "❌ Missing: BUILD_ID" && exit 1)
          test -d output/.next/static && echo "✅ Found: .next/static/" || (echo "❌ Missing: .next/static/" && exit 1)
          test -f output/package.json && echo "✅ Found: package.json" || (echo "❌ Missing: package.json" && exit 1)
          if [ -d output/public ]; then
            echo "✅ Found: public/"
          else
            echo "⚠️ Skipping: public/ not found (optional)"
          fi
          echo "✅ All required files are present. Ready for deployment."

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: output/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE16A493BCEC4957A975918EE122D892 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F36D0DD8491A436F81E6C1DE57CD8F29 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBCC9DD9DE7A40418012124A20C92093 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          package: next-app/
